apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: sudhirdockerrepo
        image: sudhirgurav24/sudhirdockerrepo:latest
          imagePullPolicy: Always
         name: myapp
         ports:
         - containerPort: 80
       imagePullSecrets:
         - name: regcred
        env:
        - name: REDIS
          value: "myapp"
 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: myapp
 spec:
   type: "LoadBalancer"
   ports:
   - name: "http"
     protocol: TCP
     port: 80
     targetPort: 80
   selector:
     name: myapp
